databases:
  - name: itsuki9029postgresql
    databaseName: itsuki9029postgresql
    user: habit-tracker
    region: singapore
    plan: free

services:
  - type: web
    name: habit-tracker
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: itsuki9029postgresql
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
