default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db
  port: 3306

development:
  <<: *default
  database: railsapp_development

test:
  <<: *default
  database: railsapp_test

production:
  <<: *default
  database: railsapp_production
  username: railsapp
  password: <%= ENV["RAILSAPP_DATABASE_PASSWORD"] %>
